[workspace]
members = [
    "packages/core",
    "packages/cli",
    "apps/macos/NextDownloader/NextDownloaderCore"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["NextDownloader Team"]
edition = "2021"
