// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_app/test/core/data/datasources/rust_bridge_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

import 'rust_bridge_datasource_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FlutterRustBridgeApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterRustBridgeApi extends _i1.Mock
    implements _i2.FlutterRustBridgeApi {
  MockFlutterRustBridgeApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> initializeDownloader() =>
      (super.noSuchMethod(
            Invocation.method(#initializeDownloader, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String> startDownload(
    String? url,
    String? destination,
    String? optionsJson,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startDownload, [url, destination, optionsJson]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#startDownload, [
                  url,
                  destination,
                  optionsJson,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> startAuthenticatedDownload(
    String? url,
    String? destination,
    String? cookiesPath,
    String? optionsJson,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startAuthenticatedDownload, [
              url,
              destination,
              cookiesPath,
              optionsJson,
            ]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#startAuthenticatedDownload, [
                  url,
                  destination,
                  cookiesPath,
                  optionsJson,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> getDownloadProgress(String? downloadId) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadProgress, [downloadId]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getDownloadProgress, [downloadId]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<bool> pauseDownload(String? downloadId) =>
      (super.noSuchMethod(
            Invocation.method(#pauseDownload, [downloadId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> resumeDownload(String? downloadId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeDownload, [downloadId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> cancelDownload(String? downloadId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelDownload, [downloadId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String> getDownloadList() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadList, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getDownloadList, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> detectContentType(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#detectContentType, [url]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#detectContentType, [url]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> getYoutubeVideoInfo(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getYoutubeVideoInfo, [url]),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getYoutubeVideoInfo, [url]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(this, Invocation.method(#getSettings, [])),
            ),
          )
          as _i3.Future<String>);
}
