name: next_downloader
description: A cross-platform video downloader application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  file_picker: ^5.3.1
  url_launcher: ^6.1.12
  dio: ^5.3.0
  uuid: ^3.0.7
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  window_manager: ^0.3.4
  desktop_drop: ^0.4.1
  desktop_window: ^0.4.0
  flutter_acrylic: ^1.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700